<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE CONFIG [
                  <!ELEMENT CONFIG (SELECT*, INSERT*)>
                  <!ELEMENT INSERT (KEY, COLUMN*)>
                  <!ELEMENT KEY EMPTY>
                  <!ELEMENT COLUMN EMPTY>

                  <!ATTLIST INSERT name ID #REQUIRED
                                   table CDATA #REQUIRED
                                   errorLevel (ERROR|WARNING) "ERROR"
                                   specifyUser (true|false) "false">
                  <!ATTLIST KEY name CDATA #REQUIRED 
                                format (number|char) "char"
                                type (record|new) "new"
                                data CDATA #REQUIRED>
                  <!ATTLIST COLUMN name CDATA #REQUIRED
                                   format (number|char|date|flag) "char"
                                   nullable (true|false) "true"
                                   type (record|absolute) "record"
                                   data CDATA #REQUIRED
                                   description CDATA #IMPLIED>
]>
<!--Descrive al processor InsertData la struttura della tabella AN_AZIENDA per potervi inserire i dati e dove trovarli
	nella Map del record.-->
<CONFIG>
	<INSERT name="AZIENDA" table="AN_AZIENDA" specifyUser="true">
		<KEY name="PRGAZIENDA" format="number" data="PRGAZIENDA" />
		<COLUMN name="STRCODICEFISCALE" nullable="false"
			data="STRAZCODICEFISCALE" description="Codice fiscale dell'azienda" />
		<COLUMN name="STRPARTITAIVA" data="STRAZPARTITAIVA"
			description="Partita iva dell'azienda" />
		<COLUMN name="STRRAGIONESOCIALE" nullable="false"
			data="STRAZRAGIONESOCIALE"
			description="Ragione sociale dell'azienda" />
		<COLUMN name="CODNATGIURIDICA" type="absolute" data="null"
			description="Natura giuridica dell'azienda" />
		<COLUMN name="CODTIPOAZIENDA" nullable="false"
			data="CODAZTIPOAZIENDA" description="Tipo di azienda" />
		<COLUMN name="STRSITOINTERNET" type="absolute" data="null"
			description="Sito Internet dell'azienda" />
		<COLUMN name="STRDESCATTIVITA" type="absolute" data="null"
			description="Descrizione attività dell'azienda" />
		<!--<COLUMN name="CODCCNL" data="CODAZCCNL" description="CCNL dell'azienda"/>  -->
		<COLUMN name="NUMSOCI" format="number" type="absolute"
			data="null" description="Numero di soci dell'azienda" />
		<COLUMN name="NUMDIPENDENTI" format="number"
			data="NUMAZDIPENDENTI"
			description="Numero di dipendenti dell'azienda" />
		<COLUMN name="NUMCOLLABORATORI" format="number" type="absolute"
			data="null" description="Numero di collaboratori dell'azienda" />
		<COLUMN name="NUMALTRAPOSIZIONE" format="number" type="absolute"
			data="null" description="Numero di altre posizioni dell'azienda" />
		<COLUMN name="DATINIZIO" format="date" type="absolute"
			data="null" description="Data di inizio dell'azienda" />
		<COLUMN name="DATFINE" format="date" type="absolute" data="null"
			description="Data di fine dell'azienda" />
		<COLUMN name="STRNOTE" type="absolute" data="null"
			description="Note sull'azienda" />
		<COLUMN name="STRNUMALBOINTERINALI"
			data="STRAZNUMALBOINTERINALI"
			description="Numero di iscrizione all'albo interinale dell'azienda" />
		<COLUMN name="STRPATINAIL" data="STRPATINAIL"
			description="PAT Inail dell'azienda" />
		<!-- DAVIDE 31/05/20078: nuovi campi tracciato UNICO -->
		<COLUMN name="STRNUMAGSOMMINISTRAZIONE"
			data="STRNUMAGSOMMINISTRAZIONE"
			description="Numero di agenzia di somministrazzione" />
	</INSERT>
	<INSERT name="UNITA_PRODUTTIVA" table="AN_UNITA_AZIENDA"
		specifyUser="true">
		<KEY name="PRGUNITA" format="number" type="record"
			data="PRGUNITAPRODUTTIVA" />
		<COLUMN name="PRGAZIENDA" nullable="false" format="number"
			data="PRGAZIENDA" description="Progressivo della testata aziendale" />
		<COLUMN name="STRREA" type="absolute" data="null"
			description="Numero REA dell'unita aziendale" />
		<COLUMN name="STRINDIRIZZO" nullable="false"
			data="STRUAINDIRIZZO" description="Indirizzo dell'unita produttiva" />
		<COLUMN name="STRLOCALITA" type="absolute" data="null"
			description="Località dell'unita produttiva" />
		<COLUMN name="CODCOM" nullable="false" data="CODUACOM"
			description="Comune dell'unita produttiva" />
		<COLUMN name="STRCAP" data="STRUACAP"
			description="Cap dell'unita produttiva" />
		<COLUMN name="FLGMEZZIPUB" type="absolute" data="null"
			description="Flag dei mezzi pubblici dell'unita produttiva" />
		<COLUMN name="FLGSEDE" data="FLGSEDE"
			description="flag sede legale dell'unita produttiva" />
		<COLUMN name="CODAZSTATO" nullable="false" type="absolute"
			data="1" description="Stato aziendale dell'unita produttiva" />
		<COLUMN name="STRRESPONSABILE" type="absolute" data="null"
			description="Responsabile dell'unita produttiva" />
		<COLUMN name="STRTEL" data="STRUATEL"
			description="Telefono dell'unita produttiva" />
		<COLUMN name="STRFAX" data="STRUAFAX"
			description="Fax dell'unita produttiva" />
		<COLUMN name="STREMAIL" data="STRUAEMAIL"
			description="E-mail dell'unita produttiva" />
		<COLUMN name="CODATECO" nullable="false" data="CODAZATECO"
			description="Codice attivita dell'unita produttiva" />
		<COLUMN name="DATINIZIO" format="date" type="absolute"
			data="null" description="Data di inizio dell'unita produttiva" />
		<COLUMN name="DATFINE" format="date" type="absolute" data="null"
			description="Data di fine dell'unita produttiva" />
		<COLUMN name="STRNOTE" type="absolute" data="null"
			description="Note sull'unita produttiva" />
		<COLUMN name="STRRIFERIMENTOSARE" data="STRREFERENTE"
			description="Identificativo del soggetto che effettua la comunicazione (Rilasciato dalla Pubblica Amm.)" />
		<COLUMN name="STRNUMREGISTROCOMMITT"
			data="STRNUMREGISTROCOMMITT"
			description="Numero del registro committenti dell'unita produttiva" />
		<COLUMN name="DATREGISTROCOMMIT" data="DATREGISTROCOMMITT"
			description="Data del registro committenti dell'unita produttiva" />
		<COLUMN name="STRNUMEROINPS" data="STRPOSINPS"
			description="Posizione INPS dell'unita produttiva" />
		<COLUMN name="CODCCNL" nullable="false" data="CODAZCCNL"
			description="CCNL dell'azienda" />
		<COLUMN name="STRCFAZESTERA" data="CODFISCAZESTERA"
			description="Codice fiscale azienda somm. estera" />
		<COLUMN name="STRRAGSOCAZESTERA" data="RAGSOCAZESTERA"
			description="Rag. sociale azienda somm. estera" />
	</INSERT>
	<INSERT name="SEDE_LEGALE" table="AN_UNITA_AZIENDA"
		errorLevel="WARNING" specifyUser="true">
		<KEY name="PRGUNITA" format="number" type="record"
			data="PRGSEDELEGALE" />
		<COLUMN name="PRGAZIENDA" nullable="false" format="number"
			data="PRGAZIENDA" description="Progressivo della testata aziendale" />
		<COLUMN name="STRREA" type="absolute" data="null"
			description="Numero REA della sede legale" />
		<COLUMN name="STRINDIRIZZO" nullable="false"
			data="STRUALINDIRIZZO" description="Indirizzo della sede legale" />
		<COLUMN name="STRLOCALITA" type="absolute" data="null"
			description="Località della sede legale" />
		<COLUMN name="CODCOM" nullable="false" data="CODUALCOM"
			description="Comune della sede legale" />
		<COLUMN name="STRTEL" data="STRUALTEL"
			description="Telefono della sede legale" />
		<COLUMN name="STRFAX" data="STRUALFAX"
			description="Fax della sede legale" />
		<COLUMN name="STREMAIL" data="STRUALEMAIL"
			description="E-mail della sede legale" />
		<COLUMN name="STRCAP" type="absolute" data="null"
			description="Cap della sede legale" />
		<COLUMN name="FLGMEZZIPUB" type="absolute" data="null"
			description="Flag dei mezzi pubblici della sede legale" />
		<COLUMN name="FLGSEDE" type="absolute" data="S"
			description="flag della sede legale" />
		<COLUMN name="CODAZSTATO" nullable="false" type="absolute"
			data="1" description="Stato aziendale della sede legale" />
		<COLUMN name="STRRESPONSABILE" type="absolute" data="null"
			description="Responsabile della sede legale" />
		<COLUMN name="STRREFERENTE" type="absolute" data="null"
			description="Referente della sede legale" />
		<COLUMN name="CODATECO" nullable="false" data="CODAZATECO"
			description="Codice attivita della sede legale" />
		<COLUMN name="DATINIZIO" format="date" type="absolute"
			data="null" description="Data di inizio della sede legale" />
		<COLUMN name="DATFINE" format="date" type="absolute" data="null"
			description="Data di fine della sede legale" />
		<COLUMN name="STRNOTE" type="absolute" data="null"
			description="Note sulla sede legale" />
		<COLUMN name="CODCCNL" nullable="false" data="CODAZCCNL"
			description="CCNL dell'azienda" />
	</INSERT>


	<!--Parte Aziende Interinali-->
	<INSERT name="AZIENDA_UTIL" table="AN_AZIENDA" specifyUser="true">
		<KEY name="PRGAZIENDA" format="number" data="PRGAZIENDAUTIL" />
		<COLUMN name="STRCODICEFISCALE" nullable="false"
			data="STRAZINTCODICEFISCALE"
			description="Codice fiscale dell'azienda utilizzatrice" />
		<COLUMN name="STRPARTITAIVA" data="STRAZINTPARTITAIVA"
			description="Partita iva dell'azienda utilizzatrice" />
		<COLUMN name="STRRAGIONESOCIALE" nullable="false"
			data="STRAZINTRAGIONESOCIALE"
			description="Ragione sociale dell'azienda utilizzatrice" />
		<COLUMN name="CODNATGIURIDICA" type="absolute" data="null"
			description="Natura giuridica dell'azienda utilizzatrice" />
		<COLUMN name="CODTIPOAZIENDA" nullable="false"
			data="CODAZINTTIPOAZIENDA"
			description="Tipo di azienda utilizzatrice" />
		<COLUMN name="STRSITOINTERNET" type="absolute" data="null"
			description="Sito Internet dell'azienda utilizzatrice" />
		<COLUMN name="STRDESCATTIVITA" type="absolute" data="null"
			description="Descrizione attività dell'azienda utilizzatrice" />
		<!--    <COLUMN name="CODCCNL" data="CODAZINTCCNL" description="CCNL dell'azienda utilizzatrice"/> -->
		<COLUMN name="NUMSOCI" format="number" type="absolute"
			data="null" description="Numero di soci dell'azienda utilizzatrice" />
		<COLUMN name="NUMDIPENDENTI" format="number"
			data="NUMAZINTDIPENDENTI"
			description="Numero di dipendenti dell'azienda utilizzatrice" />
		<COLUMN name="NUMCOLLABORATORI" format="number" type="absolute"
			data="null"
			description="Numero di collaboratori dell'azienda utilizzatrice" />
		<COLUMN name="NUMALTRAPOSIZIONE" format="number" type="absolute"
			data="null"
			description="Numero di altre posizioni dell'azienda utilizzatrice" />
		<COLUMN name="DATINIZIO" format="date" type="absolute"
			data="null" description="Data di inizio dell'azienda utilizzatrice" />
		<COLUMN name="DATFINE" format="date" type="absolute" data="null"
			description="Data di fine dell'azienda utilizzatrice" />
		<COLUMN name="STRNOTE" type="absolute" data="null"
			description="Note sull'azienda" />
	</INSERT>

	<INSERT name="UNITA_UTIL" table="AN_UNITA_AZIENDA"
		specifyUser="true">
		<KEY name="PRGUNITA" format="number" type="record"
			data="PRGUNITAUTIL" />
		<COLUMN name="PRGAZIENDA" nullable="false" format="number"
			data="PRGAZIENDAUTIL"
			description="Progressivo della testata aziendale" />
		<COLUMN name="STRREA" type="absolute" data="null"
			description="Numero REA dell'unita aziendale" />
		<COLUMN name="STRINDIRIZZO" nullable="false"
			data="STRUAINTINDIRIZZO"
			description="Indirizzo dell'unita utilizzatrice" />
		<COLUMN name="STRLOCALITA" type="absolute" data="null"
			description="Località dell'unita utilizzatrice" />
		<COLUMN name="CODCOM" nullable="false" data="CODUAINTCOM"
			description="Comune dell'unita utilizzatrice" />
		<COLUMN name="STRCAP" data="STRUAINTCAP"
			description="Cap dell'unita utilizzatrice" />
		<COLUMN name="FLGMEZZIPUB" type="absolute" data="null"
			description="Flag dei mezzi pubblici dell'unita utilizzatrice" />
		<COLUMN name="FLGSEDE" type="absolute" data="null"
			description="flag sede legale dell'unita utilizzatrice" />
		<COLUMN name="CODAZSTATO" nullable="false" type="absolute"
			data="1" description="Stato aziendale dell'unita utilizzatrice" />
		<COLUMN name="STRRESPONSABILE" type="absolute" data="null"
			description="Responsabile dell'unita utilizzatrice" />
		<COLUMN name="STRREFERENTE" type="absolute" data="null"
			description="Referente dell'unita utilizzatrice" />
		<COLUMN name="STRTEL" type="absolute" data="null"
			description="Telefono dell'unita utilizzatrice" />
		<COLUMN name="STRFAX" type="absolute" data="null"
			description="Fax dell'unita utilizzatrice" />
		<COLUMN name="STREMAIL" type="absolute" data="null"
			description="E-mail dell'unita utilizzatrice" />
		<COLUMN name="CODATECO" nullable="false" data="CODAZINTATECO"
			description="Codice attivita dell'unita utilizzatrice" />
		<COLUMN name="DATINIZIO" format="date" type="absolute"
			data="null" description="Data di inizio dell'unita utilizzatrice" />
		<COLUMN name="DATFINE" format="date" type="absolute" data="null"
			description="Data di fine dell'unita utilizzatrice" />
		<COLUMN name="STRNOTE" type="absolute" data="null"
			description="Note sull'unita utilizzatrice" />
		<COLUMN name="CODCCNL" nullable="false" data="CODAZINTCCNL"
			description="CCNL dell'azienda utilizzatrice" />
	</INSERT>

</CONFIG>